#Yet Another Markup Language, tab para la nueva linea
name: Ejemplo de Acciones
on: [push]
jobs:
    Primer-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Bienvenido a Github Actions"
            - run: echo "Ejecutando en ${{ runner.os }}"
            - run: echo "Datos en rama ${{ github.ref }} de ${{ github.repository }}"
            - name: Extraer codigo
              uses: actions/checkout@v2
            - run: echo "El repositorio ha sido clonado al equipo"
            - name: Listar los archivos del repo
              run: ls ${{ github.workspace }}
            
    
